### ISSUE TITLE
Research real estate and housing data

### ISSUE THREAD

**Issue by osuhomebase** [osuhomebase/NYUDataScience1001-edTech#4]
Potential Source:
[NYC Home Sales Data](http://www1.nyc.gov/site/finance/taxes/property-annualized-sales-update.page) 
* Median Home Value each year 
* YoY Median Home Value 
* 5 Year Diff 
* 10 Year Diff

**Comment by chujiewang** [comment]
http://furmancenter.org/research/sonychan/

**Comment by osuhomebase** [comment]
Great work
